### ISSUE TITLE
The Reverbreration Rod entry in the book isnt unlocked after eating the media cube

### ISSUE THREAD

**Issue by AlexCode10010** [beholderface/oneironaut#12]
exactly what the title says

**Comment by beholderface** [comment]
this is a consequence of it being locked behind the advancement for sneaking near a sculk sensor, so I'm not sure how I would get the media cube to unlock it without a mixin that just tells it to also grant that one

**Comment by beholderface** [comment]
ended up just creating a second advancement with the exact same trigger as the vanilla one
