### ISSUE TITLE
Reverberation Rod acts as a shield while conducting

### ISSUE THREAD

**Issue by abilliontrillionstars** [beholderface/oneironaut#21]
The reverb rod's getUseAction() method returns UseAction.BLOCK, which in addition to visually blocking also makes the rod function as a vanilla shield.

To reproduce, inscribe any spell into a reverberation rod and conduct it while being shot with arrows or being attacked by a player wielding an axe. Arrows will be blocked as well as melee attacks, even yielding no cooldown when being attacked with an axe, albeit playing the "guard break" sound effect.

**Comment by beholderface** [comment]
Confirmed that its use of `UseAction.BLOCK` is the culprit, now testing the other available `UseAction` options to find one that looks good and doesn't have obvious side effects
