### ISSUE TITLE
Add config to remove limitation on Spatial Interchange regarding blocks with significant data

### ISSUE THREAD

**Issue by Player505** [beholderface/oneironaut#8]
Basically as the title says, a way to allow the player to interchange blocks with significant data.

**Comment by beholderface** [comment]
Not working on block entities is a technical limitation at the moment, rather than a balance decision.

**Comment by beholderface** [comment]
this is no longer the case

**Comment by Player505** [comment]
Wow thank you for the quick fix

**Comment by beholderface** [comment]
¯\_(ツ)_/¯ it was something I had planned on doing eventually for a while
